spring:
  application:
    name: auth-service

server:
  port: 8088
  contextPath: /auth
  
token:
  secret: aaabbb
  expire:
    period: 1200000
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
     leaseRenewalIntervalInSeconds: 5